<div class="container-fluid">
  <form action="/" method="get">
  <div class="form-group">
    <input type="text" class="form-control" name="command" id="command" placeholder="Enter Command you want to execute!">
    <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-conditions active"><input type="checkbox" autocomplete="off" name="check" value="00" checked>linux</label>
    <!--    <label class="btn btn-conditions active"><input type="checkbox" autocomplete="off" name="check" value="01" checked>cmd</label> -->
        <label class="btn btn-conditions active"><input type="checkbox" autocomplete="off" name="check" value="02" checked>mysql</label>
        <label class="btn btn-conditions active"><input type="checkbox" autocomplete="off" name="check" value="03" checked>git</label>
    </div>
    <button name="search" id="search" class="center-block btn btn-success">Search!!</button>
  </div>
  </form>
</div>
<hr>
<div class="row container-fluid">
    <div class="container-fluid default-message">
      <div class="about">
        <div class="title text-center"><strong>About</strong></div>
          <div class="text-left">様々なコマンドを検索し、オプションごとクリップボードにコピーできます<br>オレンジボタンをOFFにすることで検索対象から除外することもできます<br>コマンドは随時追加していきます</div>
      </div>
        <hr>
      <div class="update">
        <div class="title text-center"><strong>Update</strong></div>
        <div class="col-xs-3">2017/06/18</div>
        <div class="col-xs-9 ">linux、mysql、gitのコマンドを追加しました</div>
        <div class="col-xs-3">2017/06/19</div>
        <div class="col-xs-9">"diff"コマンドを追加しました</div>
      </div>
    </div>
    <div class="selected-command col-xs-12 text-center"></div>
    <div class="command-list-area"></div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script>
$(function() {
  // ［検索］ボタンクリックで検索開始
  $('#search').click(function(event) {
    var formData = $('form').serialize();
    //通常のアクションをキャンセルする
    event.preventDefault();
    // .phpファイルへのアクセス
    $.ajax('/command/ajax',
      {
        type: 'GET',
        data: formData,
        dataType: 'json',
        success:function(data){

            //結果エリアのクリア
            $(".selected-group").empty();
            $(".selected-command").empty();
            $(".command-list-area").empty();
            $(".default-message").empty();
            $(".default-message").append(
                '該当するコマンドはありませんでした'
            );

            var group = '';

            switch (data[0].group_cd){
                case '00':
                    group = 'linux';
                    break;
                case '01':
                    group = 'cmd';
                    break;
                case '02':
                    group = 'mysql';
                    break;
                case '03':
                    group = 'git';
                    break;
            }

            $.each(data, function(i) {

                if(i==0) {
                    //メッセージのクリア
                    $(".default-message").empty();

                    $(".selected-command").append(
                        '<p><strong>' +
                        data[i].original_command_name +
                        '</strong></p>' +
                        '<span class=selected-group>' + group + '</span>' +
                        '  ' +
                        data[i].command_explain_desc
                    );
                }

                //リスト表示
                $(".command-list-area").append(
                     '<div class="command-list container-fluid">' +
                        '<div class="container-fluid">' +
                            '<div class="command-detail command col-xs-12"><input type="text" id="command-' + i + '" value="' + data[i].option_name + '" readonly="readonly"></div>' +
                        '</div>' +
                        '<div class="container-fluid">' +
                            '<div class="command-detail command text-left col-xs-10">' + data[i].explain_desc + '</div>' +
                            '<div class="command-detail col-xs-2"><button class="btn btn-warning copy" data-clipboard-target="#command-' + i + '">Copy!</button></div>' +
                        '</div>' +
                    '</div>'
                );
            });
        },
        error:function(){alert('失敗');}
      }
    )
  });
});
</script>
<link href="/css/jquery-ui.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/jquery-ui.min.js"></script>
<script>
$(document).ready( function() {
    $("#command").autocomplete({
        source: function(req, resp){

            //選択されたチェックボックスの値を配列に保存
            var checks=[];
            $("[name='check']:checked").each(function(){
                checks.push(this.value);
            });

            $.ajax({
                url: "/command/auto",
                type: "GET",
                cache: false,
                dataType: "json",
                data: {
                    command: req.term,
                    checks: checks
                },
                success: function(o){
                    resp(o);
                },
                error: function(xhr, ts, err){
                    resp(['']);
                }
            });

        }
    });
});
</script>